<?php

namespace AppBundle\Repository;

/**
 * aboutEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class aboutEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
