app:
  resource: '@AppBundle/Controller/'

intro_action:
  path: /
  defaults: { _controller: AppBundle:Default:intro }

blog_action:
  path: /blog
  defaults: { _controller: AppBundle:Blog:blog }

registration_action:
  path: /reg
  defaults: { _controller: AppBundle:Blog:reg }

registrationq_action:
  path: /regq
  defaults: { _controller: AppBundle:Blog:regq }

rmt:
  path: /rmt
  defaults: { _controller: AppBundle:Blog:rmt}